In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats

In [47]:
df = pd.read_csv("test.csv",sep=",")

Cargamos un csv con las modas de las variables del dataset train

In [48]:
modes = pd.read_csv("modetrain.csv",sep=";")

In [50]:
df.head()

,id,var1,var2,var3,var4,var5,var6,var7,var8,var9,...,weatherVar227,weatherVar228,weatherVar229,weatherVar230,weatherVar231,weatherVar232,weatherVar233,weatherVar234,weatherVar235,weatherVar236
0,10,Z,Z,Z,N1,Z,Z,4,2,A,...,1.660920,0.0,0.0,0.134528,0.291261,0.818999,2.091104,0.428316,0.751502,0.351844
1,11,Z,Z,Z,O2,Z,Z,6,4,A,...,0.990164,0.0,0.0,0.000000,0.272525,0.729924,0.973392,0.214158,0.231232,0.196379
2,14,Z,Z,Z,D3,Z,Z,7,2,A,...,0.425877,0.0,0.0,0.525500,0.182251,1.050554,0.665575,0.963711,0.404655,0.056259
3,16,2,Z,Z,G1,Z,Z,5,3,Z,...,1.043398,0.0,0.0,0.000000,0.792026,0.659200,1.118284,0.000000,0.000000,0.601947
4,20,Z,Z,Z,E4,Z,Z,2,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Vamos a conocer las dimensiones del DataSet y si existen duplicados

In [51]:
df.shape

(450728, 301)

In [52]:
df2 = df.drop_duplicates() # conjunto df sin duplicados

In [53]:
assert df2.shape==df.shape

In [54]:
del df2

In [55]:
# Vemos si hay valores nulos en la variable id
df.id.isnull().value_counts()

False    450728
Name: id, dtype: int64

In [56]:
# Convertimos el identificador a tipo string
df.id = df.id.astype(str)

Analizamos las restantes variables

In [57]:
# Lista de campos

fieldslist = df.columns.tolist()

# Lista de variables categÃ³ricas

catfieldslist = fieldslist[1:10]

for i in catfieldslist:
    print(i)
    namefield = "df."+i
    print(df[i].unique())
    print("")
    df[i]

var1
['Z' '2' '3' '4' '1' '5']

var2
['Z' 'C' 'B' 'A']

var3
['Z' '6' '2' '4' '3' '5' '1']

var4
['N1' 'O2' 'D3' 'G1' 'E4' 'Z' 'H1' 'J5' 'E3' 'M1' 'R5' 'O1' 'J1' 'F1' 'C1'
 'A1' 'R6' 'R7' 'D1' 'R3' 'E1' 'I1' 'D2' 'P1' 'K1' 'L1' 'H3' 'E5' 'G2' 'J4'
 'E2' 'H2' 'J3' 'B1' 'S1' 'R1' 'J2' 'E6' 'R2' 'D4' 'R8' 'R4' 'J6']

var5
['Z' 'B' 'D' 'C' 'A' 'F' 'E']

var6
['Z' 'C' 'B' 'A']

var7
['4' '6' '7' '5' '2' '3' '1' '8' 'Z' 1L 2L 3L 4L 5L 7L 6L 8L]

var8
['2' '4' '3' '1' '6' 'Z' '5']

var9
['A' 'Z' 'B']

Los valores Z representan los nulos y se tratarÃ¡ como una categorÃ­a mas
La variable var7 presenta valores nÃºmericos y de texto, asumiendo que son
equivalentes, pondremos todos los valores como texto

In [58]:
df.var7=df.var7.astype(str)

In [59]:
# Variables NumÃ©ricas
numericlist = fieldslist[11:19]

# ComprobaciÃ³n de valores nulos en las variables

for i in numericlist:
    print(i)
    namefield = "df."+i
    print(df[i].isnull().unique())
    print("")
    df[i]

var11
[False]

var12
[True False]

var13
[False]

var14
[True False]

var15
[False True]

var16
[True False]

var17
[False]

dummy
[False]

Las variables var12,var14,var15,var16 presentan valores nulos
que se sustituyen por la moda de cada variable, pero del dataset de train

In [60]:
var12mode = modes.loc[0,'var12']
var14mode = modes.loc[0,'var14']
var15mode = modes.loc[0,'var15']
var16mode = modes.loc[0,'var16']

df.var12 = df.var14.fillna(var14mode)
df.var14 = df.var14.fillna(var14mode)
df.var15 = df.var15.fillna(var15mode)
df.var16 = df.var16.fillna(var16mode)

Variables NumÃ©ricas de criminalidad

In [61]:
crimevars = []
for i in fieldslist:
    if i.startswith('crime'):
               crimevars.append(i)

ComprobaciÃ³n de valores nulos en las variables

In [62]:

for i in crimevars:
    print(i)
    namefield = "df."+i
    print(df[i].isnull().unique())
    print("")
    df[i]

crimeVar1
[False True]

crimeVar2
[False True]

crimeVar3
[False True]

crimeVar4
[False True]

crimeVar5
[False True]

crimeVar6
[False True]

crimeVar7
[False True]

crimeVar8
[False True]

crimeVar9
[False True]

Sustituimos los nulos por la moda en las variables crime

In [63]:
for i in crimevars:
    print(i)
    i_mode = modes.loc[0,i]
    print(i_mode)
    df[i] = df[i].fillna(i_mode)

crimeVar1
0.8686512229
crimeVar2
0.6251862044
crimeVar3
0.6855345902
crimeVar4
0.6988892091
crimeVar5
1.3226499599
crimeVar6
1.0369530604
crimeVar7
0.7398308722
crimeVar8
1.2330044911
crimeVar9
0.9858519325

Variable dummy que no entra al modelo

In [64]:
df.dummy.unique()

array(['A', 'B'], dtype=object)

Variables NumÃ©ricas geodemogrÃ¡ficas

In [65]:
geodemvars = []
for i in fieldslist:
    if i.startswith('geodem'):
               geodemvars.append(i)

ComprobaciÃ³n de valores nulos en las variables

In [66]:
for i in geodemvars:
    print(i)
    print(df[i].isnull().unique())
    print("")
    df[i]

geodemVar1
[False True]

geodemVar2
[False True]

geodemVar3
[False True]

geodemVar4
[False True]

geodemVar5
[False True]

geodemVar6
[False True]

geodemVar7
[False True]

geodemVar8
[False True]

geodemVar9
[False True]

geodemVar10
[False True]

geodemVar11
[False True]

geodemVar12
[False True]

geodemVar13
[False True]

geodemVar14
[False True]

geodemVar15
[False True]

geodemVar16
[False True]

geodemVar17
[False True]

geodemVar18
[False True]

geodemVar19
[False True]

geodemVar20
[False True]

geodemVar21
[False True]

geodemVar22
[False True]

geodemVar23
[False True]

geodemVar24
[False True]

geodemVar25
[False True]

geodemVar26
[False True]

geodemVar27
[False True]

geodemVar28
[False True]

geodemVar29
[False True]

geodemVar30
[False True]

geodemVar31
[False True]

geodemVar32
[False True]

geodemVar33
[False True]

geodemVar34
[False True]

geodemVar35
[False True]

geodemVar36
[False True]

geodemVar37
[False True]

Sustituimos los nulos por la moda en las variables geodemogrÃ¡ficas

In [67]:
for i in geodemvars:
    print(i)
    i_mode = modes.loc[0,i]
    print(i_mode)
    df[i] = df[i].fillna(i_mode)

geodemVar1
7.3890578832
geodemVar2
1.1270957102
geodemVar3
1.1735784556
geodemVar4
0.9817835101
geodemVar5
7.9367599053
geodemVar6
7.3198929331
geodemVar7
0.8320533527
geodemVar8
8.0661893496
geodemVar9
1.0530160882
geodemVar10
8.6880134873
geodemVar11
8.5636161128
geodemVar12
0.6584255057
geodemVar13
8.3305728305
geodemVar14
0.9243408844
geodemVar15
7.4936188345
geodemVar16
0.8596425947
geodemVar17
8.1422164995
geodemVar18
3.3043314078
geodemVar19
1.0012661466
geodemVar20
0.0
geodemVar21
9.4703818767
geodemVar22
0.922754749
geodemVar23
0.9948257395
geodemVar24
0.97884262
geodemVar25
1.1500012499
geodemVar26
8.8523578634
geodemVar27
8.440231214
geodemVar28
7.6117972319
geodemVar29
0.0233987714
geodemVar30
1.2064256016
geodemVar31
0.3964678862
geodemVar32
4.4023403554
geodemVar33
7.807255389
geodemVar34
0.843524736
geodemVar35
9.4415651761
geodemVar36
0.0
geodemVar37
1.2364204065

Variables NumÃ©ricas de MeteorologÃ­a

In [68]:
weathervars = []
for i in fieldslist:
    if i.startswith('weather'):
               weathervars.append(i)

ComprobaciÃ³n de valores nulos en las variables de meteorologÃ­a

In [69]:
for i in weathervars:
    print(i)
    print(df[i].isnull().unique())
    print("")
    df[i]

weatherVar1
[False True]

weatherVar2
[False True]

weatherVar3
[False True]

weatherVar4
[False True]

weatherVar5
[False True]

weatherVar6
[False True]

weatherVar7
[False True]

weatherVar8
[False True]

weatherVar9
[False True]

weatherVar10
[False True]

weatherVar11
[False True]

weatherVar12
[False True]

weatherVar13
[False True]

weatherVar14
[False True]

weatherVar15
[False True]

weatherVar16
[False True]

weatherVar17
[False True]

weatherVar18
[False True]

weatherVar19
[False True]

weatherVar20
[False True]

weatherVar21
[False True]

weatherVar22
[False True]

weatherVar23
[False True]

weatherVar24
[False True]

weatherVar25
[False True]

weatherVar26
[False True]

weatherVar27
[False True]

weatherVar28
[False True]

weatherVar29
[False True]

weatherVar30
[False True]

weatherVar31
[False True]

weatherVar32
[False True]

weatherVar33
[False True]

weatherVar34
[False True]

weatherVar35
[False True]

weatherVar36
[False True]

weatherVar37
[False True]

weatherVar38
[False True]

weatherVar39
[False True]

weatherVar40
[False True]

weatherVar41
[False True]

weatherVar42
[False True]

weatherVar43
[False True]

weatherVar44
[False True]

weatherVar45
[False True]

weatherVar46
[False True]

weatherVar47
[False True]

weatherVar48
[False True]

weatherVar49
[False True]

weatherVar50
[False True]

weatherVar51
[False True]

weatherVar52
[False True]

weatherVar53
[False True]

weatherVar54
[False True]

weatherVar55
[False True]

weatherVar56
[False True]

weatherVar57
[False True]

weatherVar58
[False True]

weatherVar59
[False True]

weatherVar60
[False True]

weatherVar61
[False True]

weatherVar62
[False True]

weatherVar63
[False True]

weatherVar64
[False True]

weatherVar65
[False True]

weatherVar66
[False True]

weatherVar67
[False True]

weatherVar68
[False True]

weatherVar69
[False True]

weatherVar70
[False True]

weatherVar71
[False True]

weatherVar72
[False True]

weatherVar73
[False True]

weatherVar74
[False True]

weatherVar75
[False True]

weatherVar76
[False True]

weatherVar77
[False True]

weatherVar78
[False True]

weatherVar79
[False True]

weatherVar80
[False True]

weatherVar81
[False True]

weatherVar82
[False True]

weatherVar83
[False True]

weatherVar84
[False True]

weatherVar85
[False True]

weatherVar86
[False True]

weatherVar87
[False True]

weatherVar88
[False True]

weatherVar89
[False True]

weatherVar90
[False True]

weatherVar91
[False True]

weatherVar92
[False True]

weatherVar93
[False True]

weatherVar94
[False True]

weatherVar95
[False True]

weatherVar96
[False True]

weatherVar97
[False True]

weatherVar98
[False True]

weatherVar99
[False True]

weatherVar100
[False True]

weatherVar101
[False True]

weatherVar102
[False True]

weatherVar103
[False True]

weatherVar104
[False True]

weatherVar105
[False True]

weatherVar106
[False True]

weatherVar107
[False True]

weatherVar108
[False True]

weatherVar109
[False True]

weatherVar110
[False True]

weatherVar111
[False True]

weatherVar112
[False True]

weatherVar113
[False True]

weatherVar114
[False True]

weatherVar115
[False True]

weatherVar116
[False True]

weatherVar117
[False True]

weatherVar118
[False True]

weatherVar119
[False True]

weatherVar120
[False True]

weatherVar121
[False True]

weatherVar122
[False True]

weatherVar123
[False True]

weatherVar124
[False True]

weatherVar125
[False True]

weatherVar126
[False True]

weatherVar127
[False True]

weatherVar128
[False True]

weatherVar129
[False True]

weatherVar130
[False True]

weatherVar131
[False True]

weatherVar132
[False True]

weatherVar133
[False True]

weatherVar134
[False True]

weatherVar135
[False True]

weatherVar136
[False True]

weatherVar137
[False True]

weatherVar138
[False True]

weatherVar139
[False True]

weatherVar140
[False True]

weatherVar141
[False True]

weatherVar142
[False True]

weatherVar143
[False True]

weatherVar144
[False True]

weatherVar145
[False True]

weatherVar146
[False True]

weatherVar147
[False True]

weatherVar148
[False True]

weatherVar149
[False True]

weatherVar150
[False True]

weatherVar151
[False True]

weatherVar152
[False True]

weatherVar153
[False True]

weatherVar154
[False True]

weatherVar155
[False True]

weatherVar156
[False True]

weatherVar157
[False True]

weatherVar158
[False True]

weatherVar159
[False True]

weatherVar160
[False True]

weatherVar161
[False True]

weatherVar162
[False True]

weatherVar163
[False True]

weatherVar164
[False True]

weatherVar165
[False True]

weatherVar166
[False True]

weatherVar167
[False True]

weatherVar168
[False True]

weatherVar169
[False True]

weatherVar170
[False True]

weatherVar171
[False True]

weatherVar172
[False True]

weatherVar173
[False True]

weatherVar174
[False True]

weatherVar175
[False True]

weatherVar176
[False True]

weatherVar177
[False True]

weatherVar178
[False True]

weatherVar179
[False True]

weatherVar180
[False True]

weatherVar181
[False True]

weatherVar182
[False True]

weatherVar183
[False True]

weatherVar184
[False True]

weatherVar185
[False True]

weatherVar186
[False True]

weatherVar187
[False True]

weatherVar188
[False True]

weatherVar189
[False True]

weatherVar190
[False True]

weatherVar191
[False True]

weatherVar192
[False True]

weatherVar193
[False True]

weatherVar194
[False True]

weatherVar195
[False True]

weatherVar196
[False True]

weatherVar197
[False True]

weatherVar198
[False True]

weatherVar199
[False True]

weatherVar200
[False True]

weatherVar201
[False True]

weatherVar202
[False True]

weatherVar203
[False True]

weatherVar204
[False True]

weatherVar205
[False True]

weatherVar206
[False True]

weatherVar207
[False True]

weatherVar208
[False True]

weatherVar209
[False True]

weatherVar210
[False True]

weatherVar211
[False True]

weatherVar212
[False True]

weatherVar213
[False True]

weatherVar214
[False True]

weatherVar215
[False True]

weatherVar216
[False True]

weatherVar217
[False True]

weatherVar218
[False True]

weatherVar219
[False True]

weatherVar220
[False True]

weatherVar221
[False True]

weatherVar222
[False True]

weatherVar223
[False True]

weatherVar224
[False True]

weatherVar225
[False True]

weatherVar226
[False True]

weatherVar227
[False True]

weatherVar228
[False True]

weatherVar229
[False True]

weatherVar230
[False True]

weatherVar231
[False True]

weatherVar232
[False True]

weatherVar233
[False True]

weatherVar234
[False True]

weatherVar235
[False True]

weatherVar236
[False True]

Sustituimos los nulos por la moda en las variables meteorolÃ³gicas

In [70]:
for i in weathervars:
    print(i)
    i_mode = modes.loc[0,i]
    print(i_mode)
    df[i] = df[i].fillna(i_mode)

weatherVar1
0.0
weatherVar2
0.0
weatherVar3
1.2440726039
weatherVar4
0.0
weatherVar5
0.9817525588
weatherVar6
0.0
weatherVar7
1.3519587015
weatherVar8
0.0
weatherVar9
0.0
weatherVar10
1.1388951227
weatherVar11
0.0
weatherVar12
0.7017804992
weatherVar13
0.0
weatherVar14
1.2025237389
weatherVar15
1.3050454884
weatherVar16
1.0679271169
weatherVar17
0.0
weatherVar18
1.3418373874
weatherVar19
0.0
weatherVar20
1.0252647892
weatherVar21
1.0581069433
weatherVar22
0.0
weatherVar23
1.1565017023
weatherVar24
0.0
weatherVar25
0.151958913
weatherVar26
0.909940957
weatherVar27
1.024223231
weatherVar28
1.8231577221
weatherVar29
0.0
weatherVar30
0.0
weatherVar31
0.0
weatherVar32
1.2715805128
weatherVar33
1.0728482574
weatherVar34
0.8877330776
weatherVar35
0.6108620605
weatherVar36
0.9745479561
weatherVar37
0.0248314172
weatherVar38
0.0
weatherVar39
0.0
weatherVar40
1.2717760474
weatherVar41
0.0
weatherVar42
0.8248852713
weatherVar43
0.0
weatherVar44
1.4552155447
weatherVar45
0.0
weatherVar46
0.0
weatherVar47
1.0153603497
weatherVar48
0.0
weatherVar49
1.1959583063
weatherVar50
0.0
weatherVar51
1.2105716366
weatherVar52
1.3638143683
weatherVar53
1.3378403309
weatherVar54
0.0
weatherVar55
0.9464825544
weatherVar56
0.0
weatherVar57
0.7343832641
weatherVar58
0.920190033
weatherVar59
0.0
weatherVar60
1.2291012542
weatherVar61
0.0
weatherVar62
0.0
weatherVar63
0.0
weatherVar64
1.0234378745
weatherVar65
1.2300082495
weatherVar66
0.0
weatherVar67
0.0
weatherVar68
0.0
weatherVar69
1.3202059894
weatherVar70
1.0336524197
weatherVar71
0.875658299
weatherVar72
0.4630582159
weatherVar73
1.0044711511
weatherVar74
0.0
weatherVar75
0.0
weatherVar76
1.5273238064
weatherVar77
0.0
weatherVar78
1.3974497781
weatherVar79
0.0
weatherVar80
0.7156529005
weatherVar81
0.0
weatherVar82
0.0
weatherVar83
1.188150249
weatherVar84
0.0
weatherVar85
0.6139208393
weatherVar86
0.0
weatherVar87
1.4488312738
weatherVar88
1.6642933292
weatherVar89
1.1845025574
weatherVar90
0.0
weatherVar91
1.4021364592
weatherVar92
0.0
weatherVar93
1.3373672256
weatherVar94
1.2012285999
weatherVar95
0.0
weatherVar96
0.0
weatherVar97
0.0
weatherVar98
0.0
weatherVar99
0.0
weatherVar100
1.0259153705
weatherVar101
0.0
weatherVar102
0.0
weatherVar103
0.0
weatherVar104
0.0
weatherVar105
1.555268088
weatherVar106
1.1007656912
weatherVar107
0.9180495038
weatherVar108
0.7081391086
weatherVar109
1.0119030979
weatherVar110
0.0
weatherVar111
0.0
weatherVar112
1.1045262969
weatherVar113
0.0
weatherVar114
1.0561248822
weatherVar115
0.0
weatherVar116
1.1719902022
weatherVar117
0.0
weatherVar118
0.0
weatherVar119
0.9791666175
weatherVar120
0.0
weatherVar121
0.4084691728
weatherVar122
1.0744203444
weatherVar123
1.1448075741
weatherVar124
0.8810302279
weatherVar125
0.0
weatherVar126
1.5808685382
weatherVar127
1.1978633582
weatherVar128
1.0950306906
weatherVar129
0.0
weatherVar130
1.081078669
weatherVar131
0.0
weatherVar132
0.0
weatherVar133
0.0
weatherVar134
1.0239505591
weatherVar135
1.8147608616
weatherVar136
0.0
weatherVar137
0.0
weatherVar138
0.0
weatherVar139
1.1291246379
weatherVar140
1.0730894177
weatherVar141
0.8898271124
weatherVar142
0.5562995769
weatherVar143
0.8608465623
weatherVar144
0.0
weatherVar145
0.0
weatherVar146
1.2387938637
weatherVar147
0.0
weatherVar148
1.7620722785
weatherVar149
0.0
weatherVar150
1.328756187
weatherVar151
0.0
weatherVar152
0.0
weatherVar153
1.2029219796
weatherVar154
0.0
weatherVar155
0.8300412976
weatherVar156
0.0
weatherVar157
1.2015659172
weatherVar158
1.291953804
weatherVar159
0.9960134521
weatherVar160
0.0
weatherVar161
1.2267530647
weatherVar162
0.0
weatherVar163
0.8327133626
weatherVar164
0.952653557
weatherVar165
0.0
weatherVar166
2.3375984992
weatherVar167
0.0
weatherVar168
0.0
weatherVar169
0.0
weatherVar170
1.0232275011
weatherVar171
2.3563491839
weatherVar172
0.0
weatherVar173
0.0
weatherVar174
0.0
weatherVar175
1.2587899148
weatherVar176
1.0678077536
weatherVar177
0.7640373596
weatherVar178
0.0
weatherVar179
0.9413651299
weatherVar180
0.0
weatherVar181
1.0147343649
weatherVar182
0.4322439752
weatherVar183
0.3753524759
weatherVar184
0.3616011435
weatherVar185
0.8933619608
weatherVar186
0.9955123316
weatherVar187
0.9131782747
weatherVar188
1.057848411
weatherVar189
0.0
weatherVar190
1.0965214785
weatherVar191
1.4916205056
weatherVar192
0.9630710178
weatherVar193
1.1651932063
weatherVar194
0.7230387749
weatherVar195
0.9939092453
weatherVar196
0.9392024556
weatherVar197
1.9205740577
weatherVar198
0.9595006611
weatherVar199
0.1357089675
weatherVar200
0.0871601131
weatherVar201
0.0
weatherVar202
0.0
weatherVar203
0.0
weatherVar204
0.8947098071
weatherVar205
0.0196588181
weatherVar206
0.0
weatherVar207
0.0
weatherVar208
0.0
weatherVar209
0.1917756555
weatherVar210
0.0
weatherVar211
0.0
weatherVar212
0.0
weatherVar213
0.1230608135
weatherVar214
0.0
weatherVar215
0.0
weatherVar216
0.1275432699
weatherVar217
0.2606511598
weatherVar218
0.0
weatherVar219
0.0
weatherVar220
0.0
weatherVar221
0.0
weatherVar222
0.0
weatherVar223
0.0
weatherVar224
0.0
weatherVar225
0.4602471522
weatherVar226
0.0
weatherVar227
0.2874668639
weatherVar228
0.0
weatherVar229
0.0
weatherVar230
0.0
weatherVar231
0.0
weatherVar232
1.2280865533
weatherVar233
0.0370036301
weatherVar234
2.1951185028
weatherVar235
0.635886632
weatherVar236
0.0

ConversiÃ³n de variables categÃ³ricas en dummy

In [71]:
dfcat = pd.DataFrame(df,columns = catfieldslist)

In [72]:
dfcat.tail(7)

       var1 var2 var3 var4 var5 var6 var7 var8 var9
450721    Z    Z    Z   D3    Z    Z    2    2    B
450722    Z    Z    Z    Z    Z    Z    5    2    A
450723    Z    Z    Z   C1    Z    Z    1    2    A
450724    3    Z    Z   E3    Z    Z    3    4    Z
450725    Z    Z    Z   C1    Z    Z    2    1    A
450726    Z    Z    Z   O2    Z    Z    7    4    A
450727    Z    Z    Z   G1    Z    Z    2    3    A

In [73]:
dfcatdummies = pd.get_dummies(dfcat)

In [74]:
dfcatdummies.head(8)

,var1_1,var1_2,var1_3,var1_4,var1_5,var1_Z,var2_A,var2_B,var2_C,var2_Z,...,var8_1,var8_2,var8_3,var8_4,var8_5,var8_6,var8_Z,var9_A,var9_B,var9_Z
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [75]:
df = df.join(dfcatdummies)

In [76]:
catfieldslist

['var1', 'var2', 'var3', 'var4', 'var5', 'var6', 'var7', 'var8', 'var9']

In [77]:
dfcat

       var1 var2 var3 var4 var5 var6 var7 var8 var9
0         Z    Z    Z   N1    Z    Z    4    2    A
1         Z    Z    Z   O2    Z    Z    6    4    A
2         Z    Z    Z   D3    Z    Z    7    2    A
3         2    Z    Z   G1    Z    Z    5    3    Z
4         Z    Z    Z   E4    Z    Z    2    2    A
5         Z    Z    Z    Z    Z    Z    3    2    A
6         Z    Z    Z   D3    Z    Z    4    3    B
7         Z    Z    Z   H1    Z    Z    3    1    A
8         3    Z    Z   G1    Z    Z    7    4    Z
9         3    Z    Z   J5    Z    Z    3    3    Z
10        Z    Z    Z   O2    Z    Z    7    4    A
11        Z    Z    Z    Z    Z    Z    4    1    A
12        Z    Z    Z   E3    Z    Z    7    3    A
13        4    Z    Z   M1    B    Z    5    1    Z
14        Z    Z    Z   O2    Z    Z    5    2    A
15        Z    Z    Z   R5    Z    Z    5    3    A
16        2    Z    6   G1    B    C    5    4    Z
17        Z    Z    Z   O1    Z    Z    5    6    A
18        Z    Z    Z   H1    Z    Z    3    1    B
19        3    Z    Z   G1    D    Z    2    3    Z
20        Z    Z    Z    Z    Z    Z    2    6    A
21        Z    Z    Z   H1    Z    Z    6    4    A
22        3    Z    Z   H1    Z    Z    3    3    Z
23        Z    Z    Z   H1    C    Z    3    2    Z
24        Z    Z    Z   J1    Z    Z    3    2    A
25        Z    Z    Z   F1    Z    Z    2    1    A
26        Z    Z    Z   C1    Z    Z    4    1    A
27        Z    Z    Z    Z    Z    Z    2    1    A
28        Z    Z    Z   O2    Z    Z    4    3    A
29        Z    Z    Z   H1    Z    Z    3    1    A
...     ...  ...  ...  ...  ...  ...  ...  ...  ...
450698    3    Z    Z   H1    Z    Z    4    3    Z
450699    4    Z    2   G2    Z    A    2    4    Z
450700    Z    Z    Z   H1    Z    Z    2    1    A
450701    Z    Z    Z   O2    Z    Z    6    4    A
450702    Z    Z    Z   M1    Z    Z    3    4    A
450703    3    Z    Z   K1    Z    Z    4    4    Z
450704    Z    Z    Z   O1    Z    Z    3    1    A
450705    4    Z    4   M1    B    Z    3    1    Z
450706    Z    Z    Z   J4    Z    Z    2    2    B
450707    Z    Z    Z   H1    Z    Z    4    3    A
450708    Z    Z    Z   H1    Z    Z    4    4    B
450709    Z    Z    Z   S1    Z    Z    3    2    A
450710    Z    Z    Z   G1    Z    Z    4    3    A
450711    Z    Z    Z   D3    Z    Z    3    2    A
450712    Z    Z    Z   E3    Z    Z    6    4    A
450713    Z    Z    Z    Z    Z    Z    3    1    A
450714    Z    Z    Z    Z    Z    Z    3    6    A
450715    Z    Z    Z   M1    Z    Z    2    2    A
450716    Z    Z    Z   C1    Z    Z    1    1    A
450717    Z    Z    Z   H1    Z    Z    3    1    A
450718    Z    Z    Z   O2    Z    Z    4    4    A
450719    Z    Z    Z   D3    Z    Z    4    1    A
450720    Z    Z    Z   G1    Z    Z    5    2    A
450721    Z    Z    Z   D3    Z    Z    2    2    B
450722    Z    Z    Z    Z    Z    Z    5    2    A
450723    Z    Z    Z   C1    Z    Z    1    2    A
450724    3    Z    Z   E3    Z    Z    3    4    Z
450725    Z    Z    Z   C1    Z    Z    2    1    A
450726    Z    Z    Z   O2    Z    Z    7    4    A
450727    Z    Z    Z   G1    Z    Z    2    3    A

[450728 rows x 9 columns]

EliminaciÃ³n de las variables categÃ³ricas

In [78]:
for i in catfieldslist:
    df = df.drop(i,axis=1)

In [79]:
df.shape

(450728, 382)

In [80]:
df.head(8)

,id,var10,var11,var12,var13,var14,var15,var16,var17,dummy,...,var8_1,var8_2,var8_3,var8_4,var8_5,var8_6,var8_Z,var9_A,var9_B,var9_Z
0,10,4.171214,774.596669,0.0,1.048147,0.0,38.0,100.0,100.000000,A,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,11,4.039930,3504.665319,0.0,1.700109,0.0,9.0,100.0,93.623766,A,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,14,3.776480,561.379551,0.0,1.177410,0.0,35.0,100.0,98.009950,A,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,16,4.314082,2352.045493,0.0,2.227744,0.0,45.0,50.0,62.598345,B,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,20,3.898949,504.975247,0.0,1.177410,0.0,66.0,100.0,0.000000,A,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5,21,4.039930,1402.854233,0.0,0.000000,0.0,31.0,100.0,70.579268,A,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6,24,4.171214,1003.069788,0.0,0.000000,0.0,70.0,100.0,100.000000,A,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,26,4.171214,1564.608577,0.0,1.394959,0.0,43.0,100.0,100.000000,A,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [81]:
df.to_csv("test_clean.csv",sep=";")